package suntrix.kmp.firebase.analytics.constants

import suntrix.kmp.firebase.analytics.*

/**
 * Created by Sebastian Owodzin on 21/03/2023
 */
actual enum class ParamValue(private val nativeValue: String) {
    ACHIEVEMENT_ID(kFIRParameterAchievementID!!),
    AD_FORMAT(kFIRParameterAdFormat!!),
    AD_NETWORK_CLICK_ID(kFIRParameterAdNetworkClickID!!),
    AD_PLATFORM(kFIRParameterAdPlatform!!),
    AD_SOURCE(kFIRParameterAdSource!!),
    AD_UNIT_NAME(kFIRParameterAdUnitName!!),
    AFFILIATION(kFIRParameterAffiliation!!),
    CAMPAIGN(kFIRParameterCampaign!!),
    CHARACTER(kFIRParameterCharacter!!),
    CONTENT(kFIRParameterContent!!),
    CONTENT_TYPE(kFIRParameterContentType!!),
    COUPON(kFIRParameterCoupon!!),
    CP1(kFIRParameterCP1!!),
    CREATIVE_NAME(kFIRParameterCreativeName!!),
    CREATIVE_SLOT(kFIRParameterCreativeSlot!!),
    CURRENCY(kFIRParameterCurrency!!),
    DESTINATION(kFIRParameterDestination!!),
    DISCOUNT(kFIRParameterDiscount!!),
    END_DATE(kFIRParameterEndDate!!),
    EXTEND_SESSION(kFIRParameterExtendSession!!),
    FLIGHT_NUMBER(kFIRParameterFlightNumber!!),
    GROUP_ID(kFIRParameterGroupID!!),
    INDEX(kFIRParameterIndex!!),
    ITEMS(kFIRParameterItems!!),
    ITEM_BRAND(kFIRParameterItemBrand!!),
    ITEM_CATEGORY(kFIRParameterItemCategory!!),
    ITEM_CATEGORY2(kFIRParameterItemCategory2!!),
    ITEM_CATEGORY3(kFIRParameterItemCategory3!!),
    ITEM_CATEGORY4(kFIRParameterItemCategory4!!),
    ITEM_CATEGORY5(kFIRParameterItemCategory5!!),
    ITEM_ID(kFIRParameterItemID!!),
    ITEM_LIST_ID(kFIRParameterItemListID!!),
    ITEM_LIST_NAME(kFIRParameterItemListName!!),
    ITEM_NAME(kFIRParameterItemName!!),
    ITEM_VARIANT(kFIRParameterItemVariant!!),
    LEVEL(kFIRParameterLevel!!),
    LEVEL_NAME(kFIRParameterLevelName!!),
    LOCATION(kFIRParameterLocation!!),
    LOCATION_ID(kFIRParameterLocationID!!),
    MEDIUM(kFIRParameterMedium!!),
    METHOD(kFIRParameterMethod!!),
    NUMBER_OF_NIGHTS(kFIRParameterNumberOfNights!!),
    NUMBER_OF_PASSENGERS(kFIRParameterNumberOfPassengers!!),
    NUMBER_OF_ROOMS(kFIRParameterNumberOfRooms!!),
    ORIGIN(kFIRParameterOrigin!!),
    PAYMENT_TYPE(kFIRParameterPaymentType!!),
    PRICE(kFIRParameterPrice!!),
    PROMOTION_ID(kFIRParameterPromotionID!!),
    PROMOTION_NAME(kFIRParameterPromotionName!!),
    QUANTITY(kFIRParameterQuantity!!),
    SCORE(kFIRParameterScore!!),
    SCREEN_CLASS(kFIRParameterScreenClass!!),
    SCREEN_NAME(kFIRParameterScreenName!!),
    SEARCH_TERM(kFIRParameterSearchTerm!!),
    SHIPPING(kFIRParameterShipping!!),
    SHIPPING_TIER(kFIRParameterShippingTier!!),
    SOURCE(kFIRParameterSource!!),
    START_DATE(kFIRParameterStartDate!!),
    SUCCESS(kFIRParameterSuccess!!),
    TAX(kFIRParameterTax!!),
    TERM(kFIRParameterTerm!!),
    TRANSACTION_ID(kFIRParameterTransactionID!!),
    TRAVEL_CLASS(kFIRParameterTravelClass!!),
    VALUE(kFIRParameterValue!!),
    VIRTUAL_CURRENCY_NAME(kFIRParameterVirtualCurrencyName!!);

    actual fun nativeValue(): String = nativeValue
}