package suntrix.kmp.firebase.analytics.constants

import com.google.firebase.analytics.FirebaseAnalytics.Event

/**
 * Created by Sebastian Owodzin on 21/03/2023
 */
actual enum class EventValue(private val nativeValue: String) {
    AD_IMPRESSION(Event.AD_IMPRESSION),
    ADD_PAYMENT_INFO(Event.ADD_PAYMENT_INFO),
    ADD_SHIPPING_INFO(Event.ADD_SHIPPING_INFO),
    ADD_TO_CART(Event.ADD_TO_CART),
    ADD_TO_WISHLIST(Event.ADD_TO_WISHLIST),
    APP_OPEN(Event.APP_OPEN),
    BEGIN_CHECKOUT(Event.BEGIN_CHECKOUT),
    CAMPAIGN_DETAILS(Event.CAMPAIGN_DETAILS),
    EARN_VIRTUAL_CURRENCY(Event.EARN_VIRTUAL_CURRENCY),
    GENERATE_LEAD(Event.GENERATE_LEAD),
    JOIN_GROUP(Event.JOIN_GROUP),
    LEVEL_END(Event.LEVEL_END),
    LEVEL_START(Event.LEVEL_START),
    LEVEL_UP(Event.LEVEL_UP),
    LOGIN(Event.LOGIN),
    POST_SCORE(Event.POST_SCORE),
    PURCHASE(Event.PURCHASE),
    REFUND(Event.REFUND),
    REMOVE_FROM_CART(Event.REMOVE_FROM_CART),
    SCREEN_VIEW(Event.SCREEN_VIEW),
    SEARCH(Event.SEARCH),
    SELECT_CONTENT(Event.SELECT_CONTENT),
    SELECT_ITEM(Event.SELECT_ITEM),
    SELECT_PROMOTION(Event.SELECT_PROMOTION),
    SHARE(Event.SHARE),
    SIGN_UP(Event.SIGN_UP),
    SPEND_VIRTUAL_CURRENCY(Event.SPEND_VIRTUAL_CURRENCY),
    TUTORIAL_BEGIN(Event.TUTORIAL_BEGIN),
    TUTORIAL_COMPLETE(Event.TUTORIAL_COMPLETE),
    UNLOCK_ACHIEVEMENT(Event.UNLOCK_ACHIEVEMENT),
    VIEW_CART(Event.VIEW_CART),
    VIEW_ITEM(Event.VIEW_ITEM),
    VIEW_ITEM_LIST(Event.VIEW_ITEM_LIST),
    VIEW_PROMOTION(Event.VIEW_PROMOTION),
    VIEW_SEARCH_RESULTS(Event.VIEW_SEARCH_RESULTS);

    actual fun nativeValue() = nativeValue
}